### ISSUE TITLE
django 1.9.x compatibility

### ISSUE THREAD

**Issue by schoera** [bitmazk/django-libs#12]
with django 1.9.2 I run into an ImportError:

> File "/[path-to-site-packages]/django_libs/format_utils.py", line 19, in <module>
>     from django.utils.importlib import import_module
> ImportError: No module named importlib

In the given django version there is no importlib module anymore.
A small change like the following did the trick (for me):

```
try:
    from importlib import import_module
except ImportError:
    from django.utils.importlib import import_module

```

hope this helps
regards, schoera

**Comment by Tyrdall** [comment]
Done in 1.66.14 :)

https://github.com/bitmazk/django-libs/commit/99a538cde1a556a77fdeb3892d6be2a9e66a439c
