### ISSUE TITLE
libs_tags.py uses things that aren't available in Python 3 (django.utils.encoding.force_unicode)

### ISSUE THREAD

**Issue by Burrito-Bazooka** [bitmazk/django-libs#7]
The [Django docs](https://docs.djangoproject.com/en/1.7/ref/utils/#django.utils.encoding.force_unicode) say that django.utils.encoding.force_unicode is not available in Python 3, and errors do get raised when I try to use django_multilingual_survey on Python ~~3.2~~ 3.4 because this force_unicode doesn't exist there. Apparently it's going to be called force_text now.

https://github.com/bitmazk/django-libs/blob/9e813d362e5476eb3bd657d245a6df0ead1b8951/django_libs/templatetags/libs_tags.py#L12

Thank you for open sourcing so much of your work!

**Comment by Tyrdall** [comment]
@Burrito-Bazooka This app is optimized for Python 2.7 and Django < 1.7. I'm sorry =(

Feel free to post a pull request, but please make sure to build it backwards compatible. Thanks!

**Comment by Burrito-Bazooka** [comment]
Ah, thanks for the reply. I might do that later, glad this is probably the only reason I couldn't get things working.

**Comment by Tyrdall** [comment]
Done!
