### ISSUE TITLE
Remove South for Django 1.8

### ISSUE THREAD

**Issue by cdchen** [bitmazk/django-libs#8]
When I use django libs for Django 1.8, it will install the South. But when I run manage.py test, it will show this message:

Creating test database for alias 'default'...
There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

Could you remove South?? Thanks lots.

**Comment by mbrochh** [comment]
@cdchen can't you just remove `south` from the `INSTALLED_APPS` setting?

**Comment by Tyrdall** [comment]
This fixed.
