### ISSUE TITLE
FACTORY_FOR is deprecated in factory_boy

### ISSUE THREAD

**Issue by kevgathuku** [bitmazk/django-libs#9]
I am using this library to generate a `UserFactory` in my tests and they are currently failing with the following error
```
FactoryError: Cannot generate instances of abstract factory UserFactory; Ensure UserFactory.Meta.model is set and UserFactory.Meta.abstract is either not set or False.
```
I suspect this is due to the use of the deprecated `FACTORY_FOR` which was deprecated in version 2.4 as documented in the [Release Notes](https://factoryboy.readthedocs.org/en/latest/changelog.html#v2-4-0)
Is there any way you could support this?
Thanks in advance.

**Comment by Tyrdall** [comment]
Hej @kevgathuku this should do the trick: https://github.com/bitmazk/django-libs/commit/6bf8554a5ac4ff9f9dec6ad6a32649335a85f244

Actually we don't use ``factory_boy`` anymore in newer projects. We recommend to use ``mixer`` (https://github.com/klen/mixer)

**Comment by kevgathuku** [comment]
Thanks. I'll take a look at Mixer.
